# Generated by Django 4.2.2 on 2023-06-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocimiento', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
