# Generated by Django 4.2.2 on 2023-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_conocimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educasion',
        ),
    ]
