# Generated by Django 4.2.2 on 2023-06-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_educacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educacion',
            old_name='educasion',
            new_name='educacion',
        ),
    ]
