# Generated by Django 4.2.2 on 2023-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_rename_educasion_educacion_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='epoca',
            field=models.IntegerField(default='2010'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia',
            name='lugar',
            field=models.CharField(default='EEccgnv', max_length=20),
            preserve_default=False,
        ),
    ]
