# Generated by Django 4.2.2 on 2023-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_alter_experiencia_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=20)),
                ('epoca', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificado')),
                ('descripcion', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
