# Generated by Django 4.2.2 on 2023-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado',
            field=models.CharField(max_length=100),
        ),
    ]
