# Generated by Django 4.2.2 on 2023-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_certificado_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerca', models.TextField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='icono')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
