# Generated by Django 4.2.2 on 2023-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0010_acerca_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='La Paz', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='Bolivia', max_length=20),
            preserve_default=False,
        ),
    ]
