# Generated by Django 4.2.2 on 2023-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0012_remove_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curriculum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
