# Generated by Django 4.2.2 on 2023-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0013_usuario_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
