# Generated by Django 4.2.2 on 2023-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0014_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portafolio'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
