# Generated by Django 4.2.2 on 2023-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0015_portafolio_imagen_alter_portafolio_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='ruta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
