# Generated by Django 4.2.2 on 2023-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0016_portafolio_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='materno',
            field=models.CharField(default='Larico', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='paterno',
            field=models.CharField(default='Zapata', max_length=200),
            preserve_default=False,
        ),
    ]
